name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Checking formating with black
      run: |
        uv run black "." --check
    - name: Analysing code with ruff
      run: |
        uv run ruff check
    - name: Analysing the code with pylint
      run: |
        uv run pylint $(git ls-files '*.py')
    - name: Unit tests
      run: |
        uv run pytest
